name: childfund_evaluation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/logos/
  #Correspondientes a la evaluación del profesor
    - assets/data/indicadores.json
    - assets/data/coeficients.json
    - assets/data/tareas_familia.json
    - assets/images/0-3_cog_1.jpg
    - assets/images/0-3_cog_2.jpg
    - assets/images/0-3_cog_3.jpg
    - assets/images/0-3_com_1.jpg
    - assets/images/0-3_com_2.jpg
    - assets/images/0-3_com_3.jpg
    - assets/images/0-3_mf_1.jpg
    - assets/images/0-3_mf_2.jpg
    - assets/images/0-3_mf_3.jpg
    - assets/images/0-3_mg_1.jpg
    - assets/images/0-3_mg_2.jpg
    - assets/images/0-3_mg_3.jpg
    - assets/images/0-3_se_1.jpg
    - assets/images/0-3_se_2.jpg
    - assets/images/0-3_se_3.jpg
    - assets/images/3-6_cog_1.jpg
    - assets/images/3-6_cog_2.jpg
    - assets/images/3-6_cog_3.jpg
    - assets/images/3-6_com_1.jpg
    - assets/images/3-6_com_2.jpg
    - assets/images/3-6_com_3.jpg
    - assets/images/3-6_mf_1.jpg
    - assets/images/3-6_mf_2.jpg
    - assets/images/3-6_mf_3.jpg
    - assets/images/3-6_mg_1.jpg
    - assets/images/3-6_mg_2.jpg
    - assets/images/3-6_mg_3.jpg
    - assets/images/3-6_se_1.jpg
    - assets/images/3-6_se_2.jpg
    - assets/images/3-6_se_3.jpg
    - assets/images/6-9_cog_1.jpg
    - assets/images/6-9_cog_2.jpg
    - assets/images/6-9_cog_3.jpg
    - assets/images/6-9_com_1.jpg
    - assets/images/6-9_com_2.jpg
    - assets/images/6-9_com_3.jpg
    - assets/images/6-9_mf_1.jpg
    - assets/images/6-9_mf_2.jpg
    - assets/images/6-9_mf_3.jpg
    - assets/images/6-9_mg_1.jpg
    - assets/images/6-9_mg_2.jpg
    - assets/images/6-9_mg_3.jpg
    - assets/images/6-9_se_1.jpg
    - assets/images/6-9_se_2.jpg
    - assets/images/6-9_se_3.jpg
    - assets/images/9-12_cog_1.jpg
    - assets/images/9-12_cog_2.jpg
    - assets/images/9-12_cog_3.jpg
    - assets/images/9-12_com_1.jpg
    - assets/images/9-12_com_2.jpg
    - assets/images/9-12_com_3.jpg
    - assets/images/9-12_mf_1.jpg
    - assets/images/9-12_mf_2.jpg
    - assets/images/9-12_mf_3.jpg
    - assets/images/9-12_mg_1.jpg
    - assets/images/9-12_mg_2.jpg
    - assets/images/9-12_mg_3.jpg
    - assets/images/9-12_se_1.jpg
    - assets/images/9-12_se_2.jpg
    - assets/images/9-12_se_3.jpg
    - assets/images/12-16_cog_1.jpg
    - assets/images/12-16_cog_2.jpg
    - assets/images/12-16_cog_3.jpg
    - assets/images/12-16_com_1.jpg
    - assets/images/12-16_com_2.jpg
    - assets/images/12-16_com_3.jpg
    - assets/images/12-16_mf_1.jpg
    - assets/images/12-16_mf_2.jpg
    - assets/images/12-16_mf_3.jpg
    - assets/images/12-16_mg_1.jpg
    - assets/images/12-16_mg_2.jpg
    - assets/images/12-16_mg_3.jpg
    - assets/images/12-16_se_1.jpg
    - assets/images/12-16_se_2.jpg
    - assets/images/12-16_se_3.jpg
    - assets/images/16-20_cog_1.jpg
    - assets/images/16-20_cog_2.jpg
    - assets/images/16-20_cog_3.jpg
    - assets/images/16-20_com_1.jpg
    - assets/images/16-20_com_2.jpg
    - assets/images/16-20_com_3.jpg
    - assets/images/16-20_mf_1.jpg
    - assets/images/16-20_mf_2.jpg
    - assets/images/16-20_mf_3.jpg
    - assets/images/16-20_mg_1.jpg
    - assets/images/16-20_mg_2.jpg
    - assets/images/16-20_mg_3.jpg
    - assets/images/16-20_se_1.jpg
    - assets/images/16-20_se_2.jpg
    - assets/images/16-20_se_3.jpg
    - assets/images/20-24_cog_1.jpg
    - assets/images/20-24_cog_2.jpg
    - assets/images/20-24_cog_3.jpg
    - assets/images/20-24_com_1.jpg
    - assets/images/20-24_com_2.jpg
    - assets/images/20-24_com_3.jpg
    - assets/images/20-24_mf_1.jpg
    - assets/images/20-24_mf_2.jpg
    - assets/images/20-24_mf_3.jpg
    - assets/images/20-24_mg_1.jpg
    - assets/images/20-24_mg_2.jpg
    - assets/images/20-24_mg_3.jpg
    - assets/images/20-24_se_1.jpg
    - assets/images/20-24_se_2.jpg
    - assets/images/20-24_se_3.jpg
    - assets/images/24-36_cog_1.jpg
    - assets/images/24-36_cog_2.jpg
    - assets/images/24-36_cog_3.jpg
    - assets/images/24-36_com_1.jpg
    - assets/images/24-36_com_2.jpg
    - assets/images/24-36_com_3.jpg
    - assets/images/24-36_mf_1.jpg
    - assets/images/24-36_mf_2.jpg
    - assets/images/24-36_mf_3.jpg
    - assets/images/24-36_mg_1.jpg
    - assets/images/24-36_mg_2.jpg
    - assets/images/24-36_mg_3.jpg
    - assets/images/24-36_se_1.jpg
    - assets/images/24-36_se_2.jpg
    - assets/images/24-36_se_3.jpg
    - assets/images/36-48_cog_1.jpg
    - assets/images/36-48_cog_2.jpg
    - assets/images/36-48_cog_3.jpg
    - assets/images/36-48_com_1.jpg
    - assets/images/36-48_com_2.jpg
    - assets/images/36-48_com_3.jpg
    - assets/images/36-48_mf_1.jpg
    - assets/images/36-48_mf_2.jpg
    - assets/images/36-48_mf_3.jpg
    - assets/images/36-48_mg_1.jpg
    - assets/images/36-48_mg_2.jpg
    - assets/images/36-48_mg_3.jpg
    - assets/images/36-48_se_1.jpg
    - assets/images/36-48_se_2.jpg
    - assets/images/36-48_se_3.jpg
    - assets/images/48-60_cog_1.jpg
    - assets/images/48-60_cog_2.jpg
    - assets/images/48-60_cog_3.jpg
    - assets/images/48-60_com_1.jpg
    - assets/images/48-60_com_2.jpg
    - assets/images/48-60_com_3.jpg
    - assets/images/48-60_mf_1.jpg
    - assets/images/48-60_mf_2.jpg
    - assets/images/48-60_mf_3.jpg
    - assets/images/48-60_mg_1.jpg
    - assets/images/48-60_mg_2.jpg
    - assets/images/48-60_mg_3.jpg
    - assets/images/48-60_se_1.jpg
    - assets/images/48-60_se_2.jpg
    - assets/images/48-60_se_3.jpg
    - assets/images/60-72_cog_1.jpg
    - assets/images/60-72_cog_2.jpg
    - assets/images/60-72_cog_3.jpg
    - assets/images/60-72_com_1.jpg
    - assets/images/60-72_com_2.jpg
    - assets/images/60-72_com_3.jpg
    - assets/images/60-72_mf_1.jpg
    - assets/images/60-72_mf_2.jpg
    - assets/images/60-72_mf_3.jpg
    - assets/images/60-72_mg_1.jpg
    - assets/images/60-72_mg_2.jpg
    - assets/images/60-72_mg_3.jpg
    - assets/images/60-72_se_1.jpg
    - assets/images/60-72_se_2.jpg
    - assets/images/60-72_se_3.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
